// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3jihSvrwaCok89ozLuPDJxma329-YBQ',
    appId: '1:1013674080696:web:ea08613a4d4c38699eb74d',
    messagingSenderId: '1013674080696',
    projectId: 'vote2u-6d272',
    authDomain: 'vote2u-6d272.firebaseapp.com',
    storageBucket: 'vote2u-6d272.appspot.com',
    measurementId: 'G-Q5R36CFD5N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUMlxNXwPhneJi3hejh8n5hqhWJh4BWvk',
    appId: '1:1013674080696:ios:3f3d232e7e4447099eb74d',
    messagingSenderId: '1013674080696',
    projectId: 'vote2u-6d272',
    storageBucket: 'vote2u-6d272.appspot.com',
    androidClientId: '1013674080696-arr829akqtga4984o5enonefhe3d9pe2.apps.googleusercontent.com',
    iosClientId: '1013674080696-6uqh2nghu6dpjvi36f2m922pumr7u0nm.apps.googleusercontent.com',
    iosBundleId: 'com.example.vote2uAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG3jihSvrwaCok89ozLuPDJxma329-YBQ',
    appId: '1:1013674080696:web:eb19a3e4cad25dd09eb74d',
    messagingSenderId: '1013674080696',
    projectId: 'vote2u-6d272',
    authDomain: 'vote2u-6d272.firebaseapp.com',
    storageBucket: 'vote2u-6d272.appspot.com',
    measurementId: 'G-KSMSLZJBF2',
  );
}
